import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import { Navbar } from "@/components/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 

{
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="">
          <div className="p-5">
            <Navbar />
          </div>
          <div>{children}</div>
          <div className="p-5">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
